---
title: "diseasy.aves"
output: html_document
date: "2024-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load
```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(tibble)
library(ggpubr)
```


```{r, include=FALSE}
h2h <- read_tsv("h2h.aves", col_names = c("gene", "semLines", "semWords", "textLines", "textWords"))

z2z <- read_tsv("z2z.aves", col_names = c("gene", "semLines", "semWords", "textLines", "textWords"))

h2z <- read_tsv("h2z.aves", col_names = c("gene", "semLines", "semWords", "textLines", "textWords"))

h2h <- h2h[,1:5]
z2z <- z2z[,1:5]
h2z <- h2z[,1:5]
```

# Add averages
```{r, results='hide'}
h2h %>%
  add_row(gene = 'Mean', !!! colMeans(.[-1]))

z2z %>%
  add_row(gene = 'Mean', !!! colMeans(.[-1]))

h2z %>%
  add_row(gene = 'Mean', !!! colMeans(.[-1]))


h2hMean <- colMeans(h2h[-1])
z2zMean <-colMeans(z2z[-1])
h2zMean <-colMeans(h2z[-1])

Mean4 = as.data.frame(list(h2hMean,z2zMean,h2zMean), col.names = c("H2H","Z2Z","H2Z"))

```



```{r}
human = as.data.frame(t(h2hMean))
human = pivot_longer(human, c(semLines, semWords, textLines,textWords), names_to = "Comparison", values_to = "Value")
ggplot(human, aes(y= Value, x=Comparison))+
  geom_col()+
  labs(title="Human to Human")+
  ylim(0,1)


fish = as.data.frame(t(z2zMean))
fish = pivot_longer(fish, c(semLines, semWords, textLines,textWords), names_to = "Comparison", values_to = "Value")
ggplot(fish, aes(y= Value, x=Comparison))+
  geom_col()+
  labs(title="fish to fish")+
  ylim(0,1)

both = as.data.frame(t(h2zMean))
both = pivot_longer(both, c(semLines, semWords, textLines,textWords), names_to = "Comparison", values_to = "Value")
ggplot(both, aes(y= Value, x=Comparison))+
  geom_col()+
  labs(title="Human to fish")+
  ylim(0,1)


```


```{r, results='hide'}
h2hMean <- colMeans(h2h[-1])

h <- as.data.frame(h2hMean,row.names = c("semanticLines", "semanticWords", "textLines","textWords"))
colnames(h)<- "mean"
h <- add_column(h, comp =c("semanticLines", "semanticWords", "textLines","textWords"), species = "h2h")
h

z <- as.data.frame(z2zMean,row.names = c("semanticLines", "semanticWords", "textLines","textWords"))
colnames(z)<- "mean"
z<- add_column(z, comp =c("semanticLines", "semanticWords", "textLines","textWords"), species = "z2z")
z

b <- as.data.frame(h2zMean,row.names = c("semanticLines", "semanticWords", "textLines","textWords"))
colnames(b)<- "mean"
b<- add_column(b, comp =c("semanticLines", "semanticWords", "textLines","textWords"), species = "h2z")
b

a = h %>%
  add_row(z) %>%
  add_row(b)
a

```

```{r}
p1 <- ggplot(a)+
  geom_col(aes(x=comp, y=mean,group = species, fill = species), position = "dodge")


p2<- ggplot(a)+
  geom_col(aes(x=species, y=mean,group = comp, fill = comp), position = "dodge")


ggarrange(p1, p2, ncol=2)
```

```{r}
library(shiny)
library(tidyverse)
# other libraries here

# data loading and one-time processing here
a

# Define UI for application 
ui <- fluidPage( #create the overall page
    #UI code here
  
  titlePanel("Average Comparison Scores"),
  
  helpText("Mean scores for human to human disease descriptions, zebrafish to zebrafish phenotype, and human to zebrafish comparison for text and semantic, words or lines."),
  
  sidebarLayout(
    sidebarPanel(
      radioButtons("species", #the input variable that the value will go into
                   "Choose a species to display:",
                   choices =list("Human to Human" = "h2h",
                     "Zebrafish to Zebrafish" = 'z2z',
                     "Human to Zebrafish"= "h2z")),
        
    checkboxGroupInput("Comparison", "Choose a comparison method to display:", 
                       choices =list("Semantic + Lines" = "semLines",
                     "Semantic + Words" = "semWords",
                     "Text + Lines"= "textLines",
                     "Text + Words" = "textWords"))
      ),
    
    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("barPlot"),
      textOutput("text")
    )))
  
  


# Define server logic 
server <- function(input, output) {
    # server code here
  
    observe({
      plotTrait <- as.name(input$species)
      plotTrait2 <- as.name(input$Comparison)

      only = filter(a, species == plotTrait)
      only = filter(only, comp == plotTrait2)
    })
  
  
    output$barPlot <- renderPlot({
      
      
      
      p1<- ggplot(data=only,
                  aes(
                      x = comp, y= mean
                  )
      )
      p1 + geom_col(position = "dodge")
    })
    
    output$text <- renderText({paste("You have selected", input$species, input$Comparison, input$Data)})
    
  }
  


# Run the application 
shinyApp(ui = ui, server = server)

```

